site_name: GridLAB-D Documentation
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
  - mkdoxy:
      projects:
       gridlabd:
          src-dirs: assert autotest build climate comm commercial connection control debug generators gldcore GldEditor market matlab matpower mysql network optimize plc powerflow python reliability residential rest tape tape_file tape_memory tape_plot utitlies
          full-doc: True 
          doxy-cfg: 
            FILE_PATTERNS: "*.cpp *.h*" 
            RECURSIVE: True 
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown_include.include:
      base_path: docs/
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - admonition
  - codehilite
nav:
  - Home: index.md
  - 0.0 GridLAB-D™:
    - Contact: 0.0 GridLAB-D™\Contacts_list.md
    - Version History: 0.0 GridLAB-D™\Version History.md
    - Projects: 0.0 GridLAB-D™\projects.md
    - Publications: 0.0 GridLAB-D™\publications.md
    - Resources & Support: 0.0 GridLAB-D™\resources.md
    - Style Guide: 0.0 GridLAB-D™\style-guide.md
  - 1.0 Prospective Users:
    - Key Attributes of GridLAB-D™: 1.0 Prospective Users\GridLAB-D_Key_Attributes.md
    - Technical Overview: 1.0 Prospective Users\Technical_Overview.md
  - 2.0 New Users:
    - Getting Started: 2.0 New Users\Getting_Started_Using_GridLAB-D.md
    - Installation:
      - MySQL:
        - Database: 2.0 New Users\Installation\MySQL\Database.md
        - Mysql: 2.0 New Users\Installation\MySQL\Mysql.md
    - Theory of Operation: 2.0 New Users\theory-of-operation.md
  - 3.0 Modeling:
    - 3.1 Intro to Modeling:
      - Basic Distribution System Modeling: 3.0 Modeling\3.1 Intro to Modeling\Modeling 101 - Basic Distribution System Modeling.md
      - Built-In Distribution Models: 3.0 Modeling\3.1 Intro to Modeling\Modeling 101 - Built-In Distribution Models.md
      - Distributed Generation: 3.0 Modeling\3.1 Intro to Modeling\Modeling 101 - Distributed_Generation.md
      - GLM Models: 3.0 Modeling\3.1 Intro to Modeling\Modeling 101 - GLM Models.md
      - Modules: 3.0 Modeling\3.1 Intro to Modeling\Modeling 101 - Modules.md
      - Recorders and Players: 3.0 Modeling\3.1 Intro to Modeling\Modeling 101 - Recorders and Players.md
      - Built in schedules and loadshapes: 3.0 Modeling\3.1 Intro to Modeling\Modeling 101 - Schedules and Loadshapes.md
    - 3.2 Intermediate Modeling:
      - Advanced Distribution Models: 3.0 Modeling\3.2 Intermediate Modeling\Advanced_Distribution_Models.md
      - Aggregate Demand Response Model: 3.0 Modeling\3.2 Intermediate Modeling\Aggregate_demand_response_model.md
      - Commercial User Guide: 3.0 Modeling\3.2 Intermediate Modeling\Commercial_User_Guide.md
    - Subsecond: 3.0 Modeling\Delta_mode.md
    - Dev:Microgrids: 3.0 Modeling\Dev_Microgrids.md
    - Dev:filter: 3.0 Modeling\Dev_filter.md
    - Droop inverter: 3.0 Modeling\Droop_inverter.md
    - ETP closed form solution: 3.0 Modeling\ETP_closed_form_solution.md
    - Escape character: 3.0 Modeling\Escape_character.md
    - Evcharger: 3.0 Modeling\Evcharger.md
    - Evcharger det: 3.0 Modeling\Evcharger_det.md
    - Generators Module Guide: 3.0 Modeling\Generators_Module_Guide.md
    - Generic Schedule Object: 3.0 Modeling\Generic_Schedule_Object.md
    - History: 3.0 Modeling\History.md
    - House: 3.0 Modeling\House.md
    - HowTo:Create a movie: 3.0 Modeling\HowTo_Create_a_movie.md
    - HowTo:mysql: 3.0 Modeling\HowTo_mysql.md
    - Hybrid Electric Vehicle Chargers: 3.0 Modeling\Hybrid_Electric_Vehicle_Chargers.md
    - Impedance dump: 3.0 Modeling\Impedance_dump.md
    - Implicit enduses: 3.0 Modeling\Implicit_enduses.md
    - Industrial and agricultural loads: 3.0 Modeling\Industrial_and_agricultural_loads.md
    - Initialization: 3.0 Modeling\Initialization.md
    - Integral: 3.0 Modeling\Integral.md
    - Inverter: 3.0 Modeling\Inverter.md
    - Inverter dyn: 3.0 Modeling\Inverter_dyn.md
    - Lights: 3.0 Modeling\Lights.md
    - Link (directive): 3.0 Modeling\Link_(directive).md
    - Load Composition: 3.0 Modeling\Load_Composition.md
    - Loadshape: 3.0 Modeling\Loadshape.md
    - Macros: 3.0 Modeling\Macros.md
    - Market Auction: 3.0 Modeling\Market_Auction.md
    - Market User Guide: 3.0 Modeling\Market_User_Guide.md
    - Matlab link: 3.0 Modeling\Matlab_link.md
    - Metrics collector: 3.0 Modeling\Metrics_collector.md
    - Metrics collector writer: 3.0 Modeling\Metrics_collector_writer.md
    - Microwave: 3.0 Modeling\Microwave.md
    - Model Debugging: 3.0 Modeling\Model_Debugging.md
    - Modeling Reference:
      - Checkpoints: 3.0 Modeling\Modeling Reference\Checkpoints.md
      - Command Options: 3.0 Modeling\Modeling Reference\Command_options.md
      - Modules:
        - Assert (module): 3.0 Modeling\Modeling Reference\Modules\Assert.md
        - Climate:
          - CSV reader: 3.0 Modeling\Modeling Reference\Modules\Climate\CSV_reader_(climate_class).md
          - Climate Module: 3.0 Modeling\Modeling Reference\Modules\Climate\Climate.md
      - Units: 3.0 Modeling\Modeling Reference\Units.md
    - Modify: 3.0 Modeling\Modify.md
    - Module functions: 3.0 Modeling\Module_functions.md
    - Module globals: 3.0 Modeling\Module_globals.md
    - Mt profile: 3.0 Modeling\Mt_profile.md
    - Multi recorder: 3.0 Modeling\Multi_recorder.md
    - Multirun mode: 3.0 Modeling\Multirun_mode.md
    - Multithreaded Random Number Generation: 3.0 Modeling\Multithreaded_Random_Number_Generation.md
    - MySQL Import/Export: 3.0 Modeling\MySQL_Import_Export.md
    - NEV: 3.0 Modeling\NEV.md
    - NEVLoads: 3.0 Modeling\NEVLoads.md
    - NEVOverhead: 3.0 Modeling\NEVOverhead.md
    - NEVTransformer: 3.0 Modeling\NEVTransformer.md
    - NEVUnderground: 3.0 Modeling\NEVUnderground.md
    - Network: 3.0 Modeling\Network_Flow_Solver.md
    - Network Flow Guide: 3.0 Modeling\Network_Flow_Guide.md
    - Newton-Raphson Distribution Powerflow Solver: 3.0 Modeling\Newton-Raphson_Distribution_Powerflow_Solver.md
    - Object (directive): 3.0 Modeling\Object_(directive).md
    - Object (property): 3.0 Modeling\Object_(property).md
    - Objects:
      - Diesel dg: 3.0 Modeling\Objects\Diesel_dg.md
      - Loads: 3.0 Modeling\Objects\Loads.md
      - Solar - Solar Panel: 3.0 Modeling\Objects\Solar.md
      - Tech:Commercial: 3.0 Modeling\Objects\Tech_Commercial.md
      - Tech:Residential: 3.0 Modeling\Objects\Tech_Residential.md
      - Voltage source inverter (VSI): 3.0 Modeling\Objects\Voltage_source_inverter_(VSI).md
      - Windturb dg: 3.0 Modeling\Objects\Windturb_dg.md
      - Object (directive): 3.0 Modeling\Objects\Writing_Objects.md
      - ZIPload: 3.0 Modeling\Objects\ZIPload.md
      - House E: 3.0 Modeling\Objects\house-e.md
    - Office: 3.0 Modeling\Office.md
    - Orientation: 3.0 Modeling\Orientation.md
    - Output: 3.0 Modeling\Output.md
    - PQ CONSTANT mode diesel dg: 3.0 Modeling\PQ_CONSTANT_mode_diesel_dg.md
    - Parameter expansion: 3.0 Modeling\Parameter_expansion.md
    - Pauseat: 3.0 Modeling\Pauseat.md
    - Pcontrol: 3.0 Modeling\Pcontrol.md
    - Performance profiling: 3.0 Modeling\Performance_profiling.md
    - Player: 3.0 Modeling\Player.md
    - Player (mysql): 3.0 Modeling\Player_(mysql).md
    - Powerflow: 3.0 Modeling\Powerflow_meter.md
    - Power Flow User Guide: 3.0 Modeling\Powerflow_User_Guide.md
    - Powerflow (module): 3.0 Modeling\Powerflow_(module).md
    - Programming conventions: 3.0 Modeling\Programming_conventions.md
    - Property calculations: 3.0 Modeling\Property_calculations.md
    - Python: 3.0 Modeling\Python.md
    - RUN: 3.0 Modeling\RUN.md
    - Randomvar: 3.0 Modeling\Randomvar.md
    - Random number generator: 3.0 Modeling\Random_number_generator.md
    - Random numbers: 3.0 Modeling\Random_numbers.md
    - Range: 3.0 Modeling\Range.md
    - Real-time server: 3.0 Modeling\Real-time_server.md
    - Realtime metric: 3.0 Modeling\Realtime_metric.md
    - Realtime server: 3.0 Modeling\Realtime_server.md
    - Recorder: 3.0 Modeling\Recorder.md
    - Recorder (mysql): 3.0 Modeling\Recorder_(mysql).md
    - Redirect: 3.0 Modeling\Redirect.md
    - Refrigerator: 3.0 Modeling\Refrigerator.md
    - Reliability Module Guide: 3.0 Modeling\Reliability_Module_Guide.md
    - Reliability User Guide: 3.0 Modeling\Reliability_User_Guide.md
    - Reliability module: 3.0 Modeling\Reliability_module.md
    - Residential (module): 3.0 Modeling\Residential_(module).md
    - Residential module user's guide: 3.0 Modeling\Residential_module_user%27s_guide.md
    - Run realtime: 3.0 Modeling\Run_realtime.md
    - Running Simulations: 3.0 Modeling\Running_Simulations.md
    - Series compensator: 3.0 Modeling\Series_compensator.md
    - Skipsafe: 3.0 Modeling\Skipsafe.md
    - Transmission: 3.0 Modeling\Transmission.md
    - Tape (module): 3.0 Modeling\Tape_Module_Guide.md
    - Tape Histogram Guide: 3.0 Modeling\Tape_Histogram_Guide.md
    - Tech:CompositionMotor: 3.0 Modeling\Tech_CompositionMotor.md
    - Tech:DeltaSPIM: 3.0 Modeling\Tech_DeltaSPIM.md
    - Tech:DeltaTPIM: 3.0 Modeling\Tech_DeltaTPIM.md
    - Thermal Energy Storage model guide: 3.0 Modeling\Thermal_Energy_Storage_model_guide.md
    - Timezone: 3.0 Modeling\Timezone.md
    - Transactive Controller: 3.0 Modeling\TransactiveController.md
    - Validate: 3.0 Modeling\Validate.md
    - Finding Objects: 3.0 Modeling\finding-objects.md
    - House E: 3.0 Modeling\house-e.md
    - Performance Profiling: 3.0 Modeling\performance-profiling.md
    - Plotting Output: 3.0 Modeling\plotting-output.md
    - Theory of Operation: 3.0 Modeling\theory-of-operation.md
  - 4.0 Developing:
    - API:
      - Dev:KML: 4.0 Developing\API\Dev_KML.md
      - Dev:Link: 4.0 Developing\API\Dev_Link.md
      - Dev:Locking: 4.0 Developing\API\Dev_Locking.md
      - Dev:Solvers: 4.0 Developing\API\Dev_Solvers.md
      - Dev:load method: 4.0 Developing\API\Dev_load_method.md
      - Dev:notify: 4.0 Developing\API\Dev_notify.md
      - Extern: 4.0 Developing\API\Extern.md
      - Gld object: 4.0 Developing\API\Object.md
      - PT ACCESS: 4.0 Developing\API\PT_ACCESS.md
      - Powerflow External LU Solver Interface: 4.0 Developing\API\Powerflow_External_LU_Solver_Interface.md
      - Publishing methods: 4.0 Developing\API\Publishing_methods.md
      - Publishing properties: 4.0 Developing\API\Publishing_properties.md
      - Using Global Variables: 4.0 Developing\API\Using_Global_Variables.md
      - Module globals: 4.0 Developing\API\globals.md
    - Build_Installation:
      - CMake Build | Building GridLAB-D: 4.0 Developing\Build_Installation\Build.md
      - Building and Releasing GridLAB-D: 4.0 Developing\Build_Installation\Building_for_release.md
      - Installing GridLAB-D™: 4.0 Developing\Build_Installation\Installing.md
    - Code templates: 4.0 Developing\Code_templates.md
    - Debugging:
      - Command options: 4.0 Developing\Debugging\Command_line_arguments.md
      - Performance Profiling: 4.0 Developing\Debugging\performance-profiling.md
    - Deltamode:
      - Dev:Subsecond: 4.0 Developing\Deltamode\Dev_Subsecond.md
    - Fundamentals:
      - Class: 4.0 Developing\Fundamentals\CLASS.md
      - Core Guide: 4.0 Developing\Fundamentals\Core_Guide.md
      - Creating a class: 4.0 Developing\Fundamentals\Creating_a_class.md
      - Creating a module: 4.0 Developing\Fundamentals\Creating_a_module.md
      - Dev:HowTo:Create a module: 4.0 Developing\Fundamentals\Dev_HowTo_Create_a_module.md
      - Environment: 4.0 Developing\Fundamentals\Environment.md
      - Gld object: 4.0 Developing\Fundamentals\Gld_object.md
      - How To Write GridLAB-D Modules: 4.0 Developing\Fundamentals\How_To_Write_GridLAB-D_Modules.md
      - Integrated Testing: 4.0 Developing\Fundamentals\Integrated_Testing.md
      - Introduction to Programming GridLAB-D: 4.0 Developing\Fundamentals\Introduction_to_Programming_GridLAB-D.md
      - Mainloop state: 4.0 Developing\Fundamentals\Mainloop_state.md
      - Code templates: 4.0 Developing\Fundamentals\Module_templates.md
      - Gld property: 4.0 Developing\Fundamentals\Property.md
      - Developing 101: 4.0 Developing\Fundamentals\intro-to-developing.md
    - Modules:
      - autotest:
        - Validate: 4.0 Developing\Modules\autotest\Validate_report.md
      - connections:
        - Connection: 4.0 Developing\Modules\connections\Connection.md
        - Connection:fncs msg: 4.0 Developing\Modules\connections\Connection_fncs_msg.md
        - Connection:helics msg: 4.0 Developing\Modules\connections\Connection_helics_msg.md
        - Connection:json: 4.0 Developing\Modules\connections\Connection_json.md
        - Connection:link: 4.0 Developing\Modules\connections\Connection_link.md
        - Connection:lockout: 4.0 Developing\Modules\connections\Connection_lockout.md
        - Connection:mode: 4.0 Developing\Modules\connections\Connection_mode.md
        - Connection:native: 4.0 Developing\Modules\connections\Connection_native.md
        - Connection:security: 4.0 Developing\Modules\connections\Connection_security.md
        - Connection:transport: 4.0 Developing\Modules\connections\Connection_transport.md
        - Connection:xml: 4.0 Developing\Modules\connections\Connection_xml.md
        - Dev:connection: 4.0 Developing\Modules\connections\Dev_connection.md
        - Dev:mysql: 4.0 Developing\Modules\connections\Dev_mysql.md
      - gldcore:
        - Glengine: 4.0 Developing\Modules\gldcore\Glengine.md
      - optimization:
        - Optimize: 4.0 Developing\Modules\optimization\Optimize.md
        - Tech:Optimize: 4.0 Developing\Modules\optimization\Tech_Optimize.md
      - powerflow:
        - HowTo:Create a solver: 4.0 Developing\Modules\powerflow\HowTo_Create_a_solver.md
      - residential:
        - Tech:Multizone ETP Linearization: 4.0 Developing\Modules\residential\Tech_Multizone_ETP_Linearization.md
    - Dev:class: 4.0 Developing\Style_guide.md
  - 5.0 Integration:
    - Interfacing with External Software: 5.0 Integration\Interfacing_with_External_Software.md
    - Intro to Integration: 5.0 Integration\intro-to-integration.md
  - 6.0 Examples:
    - Placeholder: 6.0 Examples\placeholder.md
  - 7.0 References:
    - Specs:
      - Communications: 7.0 References\Specs\Spec-Communicatins.md
      - Spec:Commercial: 7.0 References\Specs\Spec_Commercial.md
      - Spec:Dishwasher: 7.0 References\Specs\Spec_Dishwasher.md
      - Spec:GUI: 7.0 References\Specs\Spec_GUI.md
      - Spec:Initialization: 7.0 References\Specs\Spec_Initialization.md
      - Spec:Market: 7.0 References\Specs\Spec_Market.md
      - Spec:Mesh Fault Current: 7.0 References\Specs\Spec_Mesh_Fault_Current.md
      - Spec:Microgrids: 7.0 References\Specs\Spec_Microgrids.md
      - Spec:Multirun mode: 7.0 References\Specs\Spec_Multirun_mode.md
      - Spec:NEV: 7.0 References\Specs\Spec_NEV.md
      - Spec:NEVArray: 7.0 References\Specs\Spec_NEVArray.md
      - Spec:NEVDataFormat: 7.0 References\Specs\Spec_NEVDataFormat.md
      - Spec:NEVLink: 7.0 References\Specs\Spec_NEVLink.md
      - Spec:NEVModules: 7.0 References\Specs\Spec_NEVModules.md
      - Spec:NEVNode: 7.0 References\Specs\Spec_NEVNode.md
      - Spec:NEVSolver: 7.0 References\Specs\Spec_NEVSolver.md
      - Spec:Optimize: 7.0 References\Specs\Spec_Optimize.md
      - Spec:Range: 7.0 References\Specs\Spec_Range.md
      - Spec:Residential: 7.0 References\Specs\Spec_Residential.md
      - Spec:Subsecond: 7.0 References\Specs\Spec_Subsecond.md
      - Spec:Transmission: 7.0 References\Specs\Spec_Transmission.md
      - Spec:ibr blackboxmodels: 7.0 References\Specs\Spec_ibr_blackboxmodels.md
      - Spec:ibr grayboxmodels: 7.0 References\Specs\Spec_ibr_grayboxmodels.md
      - Spec:inverter dyn: 7.0 References\Specs\Spec_inverter_dyn.md
      - Spec:particle swarm optimizer: 7.0 References\Specs\Spec_particle_swarm_optimizer.md
      - Spec:sec control: 7.0 References\Specs\Spec_sec_control.md
      - Spec:switch object: 7.0 References\Specs\Spec_switch_object.md
      - Spec:sync check: 7.0 References\Specs\Spec_sync_check.md
      - Spec:sync ctrl: 7.0 References\Specs\Spec_sync_ctrl.md
  - GridLAB-D Documentation Outline: docs/outline.md
  - reference:
    - ReadMeConfig:
      - authentication: reference/ReadMeConfig/authentication.md
      - getting-started: reference/ReadMeConfig/getting-started.md
      - my-requests: reference/ReadMeConfig/my-requests.md
    - Doxygen: 
        - Groups: gridlabd/group__index.md
        - Structs: gridlabd/structs__index.md
        - Files: gridlabd/files.md
        - Classes: gridlabd/classes.md
        - Hierarchy: gridlabd/hierarchy.md
        - Modules: gridlabd/modules.md
        - Pages: gridlabd/pages.md
      
        


      