site_name: GridLAB-D Documentation
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: docs/
  - admonition
nav:
  - Home: index.md
  - GridLAB-D™:
      - Introduction: docs/0.0 GridLAB-D™/Introduction.md
      - Projects: docs/0.0 GridLAB-D™/projects.md
      - Publications: docs/0.0 GridLAB-D™/publications.md
      - Resources: docs/0.0 GridLAB-D™/resources.md
      - Contacts: docs/0.0 GridLAB-D™/Contacts_list.md
      - Version History: docs/0.0 GridLAB-D™/Version History.md 
      - Style Guide: docs/0.0 GridLAB-D™/style-guide.md
  - Prospective Users: 
      - Technical Overview: docs\1.0 Prospective Users\Technical_Overview.md
      - GridLAB-D Key Attributes: docs\docs\1.0 Prospective Users\GridLAB-D_Key_Attributes.md
  - New Users:
      - MySQL: docs/2.0 New Users/Mysql.md
      - Getting Started: docs/2.0 New Users/Getting_Started_Using_GridLAB-D.md
  - Modeling:
      - Introduction: docs/3.0 Modeling/intro-to-modeling/Introduction.md
      - Advanced Distribution Models: docs/3.0 Modeling/intermediate-modeling/Advanced_Distribution_Models.md
  - Developing:
      - API:
        - Powerflow Solver: docs\4.0 Developing\API\Powerflow_External_LU_Solver_Interface.md

      