site_name: GridLAB-D Documentation
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: sphinx
  - mkdoxy:
      projects:
       gridlabd:
          src-dirs: assert autotest build climate comm commercial connection control debug generators gldcore GldEditor market matlab matpower mysql network optimize plc powerflow python reliability residential rest tape tape_file tape_memory tape_plot utitlies
          full-doc: True 
          doxy-cfg: 
            FILE_PATTERNS: "*.cpp *.h*" 
            RECURSIVE: True 
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown_include.include:
      base_path: docs/
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  - admonition
  - codehilite
nav:
  - Home: index.md
  - 0.0 GridLAB-D™:
    - Contact: docs/0.0 GridLAB-D™/Contacts_list.md
    - Version History: docs/0.0 GridLAB-D™/Version History.md
    - Projects: docs/0.0 GridLAB-D™/projects.md
    - Publications: docs/0.0 GridLAB-D™/publications.md
    - Resources & Support: docs/0.0 GridLAB-D™/resources.md
    - Style Guide: docs/0.0 GridLAB-D™/style-guide.md
  - 1.0 Prospective Users:
    - Key Attributes of GridLAB-D™: docs/1.0 Prospective Users/GridLAB-D_Key_Attributes.md
    - Technical Overview: docs/1.0 Prospective Users/Technical_Overview.md
  - 2.0 New Users:
    - Getting Started: docs/2.0 New Users/Getting_Started_Using_GridLAB-D.md
    - Installation:
      - MySQL:
        - Database: docs/2.0 New Users/Installation/MySQL/Database.md
        - HowTo:mysql: docs/2.0 New Users/Installation/MySQL/HowTo_mysql.md
        - MySQL Import/Export: docs/2.0 New Users/Installation/MySQL/MySQL_Import_Export.md
        - Mysql: docs/2.0 New Users/Installation/MySQL/Mysql.md
    - Theory of Operation: docs/2.0 New Users/theory-of-operation.md
  - 3.0 Modeling:
    - 3.1 Intro to Modeling:
      - Basic Distribution System Modeling: docs/3.0 Modeling/3.1 Intro to Modeling/Modeling 101 - Basic Distribution System Modeling.md
      - Built-In Distribution Models: docs/3.0 Modeling/3.1 Intro to Modeling/Modeling 101 - Built-In Distribution Models.md
      - Distributed Generation: docs/3.0 Modeling/3.1 Intro to Modeling/Modeling 101 - Distributed_Generation.md
      - GLM Models: docs/3.0 Modeling/3.1 Intro to Modeling/Modeling 101 - GLM Models.md
      - Modules: docs/3.0 Modeling/3.1 Intro to Modeling/Modeling 101 - Modules.md
      - Recorders and Players: docs/3.0 Modeling/3.1 Intro to Modeling/Modeling 101 - Recorders and Players.md
      - Built-in Schedules and Loadshapes: docs/3.0 Modeling/3.1 Intro to Modeling/Modeling 101 - Schedules and Loadshapes.md
      - Running Simulations: docs/3.0 Modeling/3.1 Intro to Modeling/Running_Simulations.md
    - 3.2 Intermediate Modeling:
      - Advanced Distribution Models: docs/3.0 Modeling/3.2 Intermediate Modeling/Advanced_Distribution_Models.md
      - Aggregate Demand Response Model: docs/3.0 Modeling/3.2 Intermediate Modeling/Aggregate_demand_response_model.md
      - Commercial User Guide: docs/3.0 Modeling/3.2 Intermediate Modeling/Commercial_User_Guide.md
      - Microgrids: docs/3.0 Modeling/3.2 Intermediate Modeling/Dev_Microgrids.md
      - ETP closed form solution: docs/3.0 Modeling/3.2 Intermediate Modeling/ETP_closed_form_solution.md
      - Load Composition: docs/3.0 Modeling/3.2 Intermediate Modeling/Load_Composition.md
      - Loadshape: docs/3.0 Modeling/3.2 Intermediate Modeling/Loadshape.md
      - Model Debugging: docs/3.0 Modeling/3.2 Intermediate Modeling/Model_Debugging.md
      - Neutral Earth Voltage (NEV): docs/3.0 Modeling/3.2 Intermediate Modeling/NEV.md
      - Newton-Raphson Distribution Powerflow Solver: docs/3.0 Modeling/3.2 Intermediate Modeling/Newton-Raphson_Distribution_Powerflow_Solver.md
      - Power Flow User Guide: docs/3.0 Modeling/3.2 Intermediate Modeling/Power_Flow_User_Guide.md
      - Reliability User Guide: docs/3.0 Modeling/3.2 Intermediate Modeling/Reliability_User_Guide.md
      - Transmission: docs/3.0 Modeling/3.2 Intermediate Modeling/TDIntegration.md
      - Tech:Commercial: docs/3.0 Modeling/3.2 Intermediate Modeling/Tech_Commercial.md
      - Tech:Residential: docs/3.0 Modeling/3.2 Intermediate Modeling/Tech_Residential.md
    - Deprecated:
      - Network: docs/3.0 Modeling/Deprecated/Network_Flow_Solver.md
      - Network Flow Guide: docs/3.0 Modeling/Deprecated/Network_Flow_Guide.md
    - Miscellaneous:
      - HowTo:Create a movie: docs/3.0 Modeling/Miscellaneous/HowTo_Create_a_movie.md
    - Modeling Reference:
      - Checkpoints: docs/3.0 Modeling/Modeling Reference/Checkpoints.md
      - Command Options: docs/3.0 Modeling/Modeling Reference/Command_options.md
      - Subsecond: docs/3.0 Modeling/Modeling Reference/Delta_mode.md
      - Droop inverter: docs/3.0 Modeling/Modeling Reference/Droop_inverter.md
      - Industrial and agricultural loads: docs/3.0 Modeling/Modeling Reference/Industrial_and_agricultural_loads.md
      - Model Initialization: docs/3.0 Modeling/Modeling Reference/Initialization.md
      - Link (directive): docs/3.0 Modeling/Modeling Reference/Link_(directive).md
      - Macros: docs/3.0 Modeling/Modeling Reference/Macros.md
      - Matlab link: docs/3.0 Modeling/Modeling Reference/Matlab_link.md
      - Modules:
        - Assert (module): docs/3.0 Modeling/Modeling Reference/Modules/Assert.md
        - Climate:
          - CSV reader: docs/3.0 Modeling/Modeling Reference/Modules/Climate/CSV_reader_(climate_class).md
          - Climate Module: docs/3.0 Modeling/Modeling Reference/Modules/Climate/Climate.md
        - Market:
          - Market Auction: docs/3.0 Modeling/Modeling Reference/Modules/Market/Market_Auction.md
          - Market User Guide: docs/3.0 Modeling/Modeling Reference/Modules/Market/Market_User_Guide.md
          - Transactive Controller: docs/3.0 Modeling/Modeling Reference/Modules/Market/TransactiveController.md
        - Module functions: docs/3.0 Modeling/Modeling Reference/Modules/Module_functions.md
        - Module globals: docs/3.0 Modeling/Modeling Reference/Modules/Module_globals.md
        - Powerflow (module): docs/3.0 Modeling/Modeling Reference/Modules/Powerflow_(module).md
        - Residential:
          - House: docs/3.0 Modeling/Modeling Reference/Modules/Residential/House.md
          - Lights: docs/3.0 Modeling/Modeling Reference/Modules/Residential/Lights.md
          - Loads: docs/3.0 Modeling/Modeling Reference/Modules/Residential/Loads.md
          - Microwave: docs/3.0 Modeling/Modeling Reference/Modules/Residential/Microwave.md
          - Range: docs/3.0 Modeling/Modeling Reference/Modules/Residential/Range.md
          - Refrigerator: docs/3.0 Modeling/Modeling Reference/Modules/Residential/Refrigerator.md
          - Residential module user's guide: docs/3.0 Modeling/Modeling Reference/Modules/Residential/Residential_Module_Guide.md
          - Thermal Energy Storage model guide: docs/3.0 Modeling/Modeling Reference/Modules/Residential/Thermal_Energy_Storage_model_guide.md
          - ZIPload: docs/3.0 Modeling/Modeling Reference/Modules/Residential/ZIPload.md
          - House E: docs/3.0 Modeling/Modeling Reference/Modules/Residential/house-e.md
        - Tape (module): docs/3.0 Modeling/Modeling Reference/Modules/Tape.md
        - mysql:
          - Player (mysql): docs/3.0 Modeling/Modeling Reference/Modules/mysql/Player_(mysql).md
          - Recorder (mysql): docs/3.0 Modeling/Modeling Reference/Modules/mysql/Recorder_(mysql).md
      - Multirun mode: docs/3.0 Modeling/Modeling Reference/Multirun_mode.md
      - Multithreaded Random Number Generation: docs/3.0 Modeling/Modeling Reference/Multithreaded_Random_Number_Generation.md
      - Parameter expansion: docs/3.0 Modeling/Modeling Reference/Parameter_expansion.md
      - Pauseat: docs/3.0 Modeling/Modeling Reference/Pauseat.md
      - Performance profiling: docs/3.0 Modeling/Modeling Reference/Performance_profiling.md
      - Player: docs/3.0 Modeling/Modeling Reference/Player.md
      - Powerflow Tehnical Reference: docs/3.0 Modeling/Modeling Reference/Power_Flow_Reference.md
      - Realtime server: docs/3.0 Modeling/Modeling Reference/Realtime_server.md
      - Series compensator: docs/3.0 Modeling/Modeling Reference/Series_compensator.md
      - Tech:CompositionMotor: docs/3.0 Modeling/Modeling Reference/Tech_CompositionMotor.md
      - Tech:DeltaSPIM: docs/3.0 Modeling/Modeling Reference/Tech_DeltaSPIM.md
      - Three Phase Induction Motors: docs/3.0 Modeling/Modeling Reference/Tech_DeltaTPIM.md
      - Units: docs/3.0 Modeling/Modeling Reference/Units.md
      - Validate: docs/3.0 Modeling/Modeling Reference/Validate.md
      - Finding Objects: docs/3.0 Modeling/Modeling Reference/finding-objects.md
      - Plotting Output: docs/3.0 Modeling/Modeling Reference/plotting-output.md
    - Objects:
      - Commercial:
        - Office: docs/3.0 Modeling/Objects/Commercial/Office.md
      - Distributed Energy Resources:
        - Diesel dg: docs/3.0 Modeling/Objects/Distributed Energy Resources/Diesel_dg.md
        - Evcharger: docs/3.0 Modeling/Objects/Distributed Energy Resources/Evcharger.md
        - Evcharger det: docs/3.0 Modeling/Objects/Distributed Energy Resources/Evcharger_det.md
        - Hybrid Electric Vehicle Chargers: docs/3.0 Modeling/Objects/Distributed Energy Resources/Hybrid_Electric_Vehicle_Chargers.md
        - Inverter: docs/3.0 Modeling/Objects/Distributed Energy Resources/Inverter.md
        - PQ CONSTANT mode diesel dg: docs/3.0 Modeling/Objects/Distributed Energy Resources/PQ_CONSTANT_mode_diesel_dg.md
        - Solar - Solar Panel: docs/3.0 Modeling/Objects/Distributed Energy Resources/Solar.md
        - Windturb dg: docs/3.0 Modeling/Objects/Distributed Energy Resources/Windturb_dg.md
      - Metrics & Recorders:
        - Metrics collector: docs/3.0 Modeling/Objects/Metrics & Recorders/Metrics_collector.md
        - Metrics collector writer: docs/3.0 Modeling/Objects/Metrics & Recorders/Metrics_collector_writer.md
        - Multi recorder: docs/3.0 Modeling/Objects/Metrics & Recorders/Multi_recorder.md
        - Recorder: docs/3.0 Modeling/Objects/Metrics & Recorders/Recorder.md
      - Object (directive): docs/3.0 Modeling/Objects/Writing_Objects.md
      - Object (property): docs/3.0 Modeling/Objects/Object_(property).md
      - Voltage source inverter (VSI): docs/3.0 Modeling/Objects/Voltage_source_inverter_(VSI).md
  - 4.0 Developing:
  - Introduction: docs/4.0 Developing/4.1 - Introduction.md
  - Building GridLAB-D from Source: docs/4.0 Developing/4.2 - Building GridLAB-D from Source.md
  - 4.3 - GridLAB-D Software Architecture:
    - GridLAB-D Software Architecture Introduction.md: docs/4.0 Developing/4.3 - GridLAB-D Software Architecture/4.3.0 - GridLAB-D Software Architecture Introduction.md
    - GLDCore: docs/4.0 Developing/4.3 - GridLAB-D Software Architecture/4.3.1 - GLD Core.md
    - Object Synchronization Process: docs/4.0 Developing/4.3 - GridLAB-D Software Architecture/4.3.2 - GridLAB-D Object Synchronization Process.md
    - GridLAB-D Modules: docs/4.0 Developing/4.3 - GridLAB-D Software Architecture/4.3.3 - GridLAB-D Modules.md
    - GridLAB-D Device Model Structure: docs/4.0 Developing/4.3 - GridLAB-D Software Architecture/4.3.4 - GridLAB-D Device Model Structure.md
    - GridLAB-D Objects: docs/4.0 Developing/4.3 - GridLAB-D Software Architecture/4.3.5 - GridLAB-D Objects.md
    - GridLAB-D Parallelization: docs/4.0 Developing/4.3 - GridLAB-D Software Architecture/4.3.6 - GridLAB-D Parallelization.md
    - GridLAB-D Loader: docs/4.0 Developing/4.3 - GridLAB-D Software Architecture/4.3.7 - GridLAB-D Loader.md
    - GridLAB-D Data Transforms: docs/4.0 Developing/4.3 - GridLAB-D Software Architecture/4.3.8 - GridLAB-D Transforms.md
    - libgld: docs/4.0 Developing/4.3 - GridLAB-D Software Architecture/4.3.9 - libgld.md
  - 4.4 - GridLAB-D Development Fundamentals:
    - Programming conventions: docs/4.0 Developing/4.4 - GridLAB-D Development Fundamentals/4.4.1 - Programming_conventions.md
    - Creating a module - v1: docs/4.0 Developing/4.4 - GridLAB-D Development Fundamentals/4.4.2 - Creating_a_module.md
    - Creating a class: docs/4.0 Developing/4.4 - GridLAB-D Development Fundamentals/4.4.3 - Creating_a_class.md
    - Integrated Testing: docs/4.0 Developing/4.4 - GridLAB-D Development Fundamentals/4.4.4 - Integrated_Testing.md
  - 4.5 - Deltamode Development:
    - Introduction to Deltamode Development: docs/4.0 Developing/4.5 - Deltamode Development/4.5.0 - Introduction to Deltamode Development.md
    - Dev:Subsecond: docs/4.0 Developing/4.5 - Deltamode Development/4.5.1 - Dev_Subsecond.md
  - 4.6- Debugging:
    - Introduction to Debugging when Developing GridLAB-Debugging: docs/4.0 Developing/4.6- Debugging/4.6.0 - Introduction.md
    - Command options: docs/4.0 Developing/4.6- Debugging/4.6.1 - Command_line_arguments.md
    - Performance Profiling: docs/4.0 Developing/4.6- Debugging/4.6.2 - performance-profiling.md
  - Dev:class: docs/4.0 Developing/4.7 - Style_guide.md
  - undecided:
    - Dev:mysql: docs/4.0 Developing/undecided/Dev_mysql.md
    - HowTo:Create a solver: docs/4.0 Developing/undecided/HowTo_Create_a_solver.md
    - Powerflow External LU Solver Interface: docs/4.0 Developing/undecided/Powerflow_External_LU_Solver_Interface.md
    - Tech:Optimize: docs/4.0 Developing/undecided/Tech_Optimize.md
  - 5.0 Integration:
    - Interfacing with External Software: docs/5.0 Integration/Interfacing_with_External_Software.md
    - Intro to Integration: docs/5.0 Integration/intro-to-integration.md
  - 6.0 Examples:
    - Placeholder: docs/6.0 Examples/placeholder.md
  - 7.0 References:
    - Specs:
      - Communications: docs/7.0 References/Specs/Spec-Communicatins.md
      - Spec:Commercial: docs/7.0 References/Specs/Spec_Commercial.md
      - Spec:Dishwasher: docs/7.0 References/Specs/Spec_Dishwasher.md
      - Spec:GUI: docs/7.0 References/Specs/Spec_GUI.md
      - Spec:Initialization: docs/7.0 References/Specs/Spec_Initialization.md
      - Spec:Market: docs/7.0 References/Specs/Spec_Market.md
      - Spec:Mesh Fault Current: docs/7.0 References/Specs/Spec_Mesh_Fault_Current.md
      - Spec:Microgrids: docs/7.0 References/Specs/Spec_Microgrids.md
      - Spec:Multirun mode: docs/7.0 References/Specs/Spec_Multirun_mode.md
      - Spec:NEV: docs/7.0 References/Specs/Spec_NEV.md
      - Spec:NEVArray: docs/7.0 References/Specs/Spec_NEVArray.md
      - Spec:NEVDataFormat: docs/7.0 References/Specs/Spec_NEVDataFormat.md
      - Spec:NEVLink: docs/7.0 References/Specs/Spec_NEVLink.md
      - Spec:NEVModules: docs/7.0 References/Specs/Spec_NEVModules.md
      - Spec:NEVNode: docs/7.0 References/Specs/Spec_NEVNode.md
      - Spec:NEVSolver: docs/7.0 References/Specs/Spec_NEVSolver.md
      - Spec:Optimize: docs/7.0 References/Specs/Spec_Optimize.md
      - Spec:Range: docs/7.0 References/Specs/Spec_Range.md
      - Spec:Residential: docs/7.0 References/Specs/Spec_Residential.md
      - Spec:Subsecond: docs/7.0 References/Specs/Spec_Subsecond.md
      - Spec:Transmission: docs/7.0 References/Specs/Spec_Transmission.md
      - Spec:ibr blackboxmodels: docs/7.0 References/Specs/Spec_ibr_blackboxmodels.md
      - Spec:ibr grayboxmodels: docs/7.0 References/Specs/Spec_ibr_grayboxmodels.md
      - Spec:inverter dyn: docs/7.0 References/Specs/Spec_inverter_dyn.md
      - Spec:particle swarm optimizer: docs/7.0 References/Specs/Spec_particle_swarm_optimizer.md
      - Spec:sec control: docs/7.0 References/Specs/Spec_sec_control.md
      - Spec:switch object: docs/7.0 References/Specs/Spec_switch_object.md
      - Spec:sync check: docs/7.0 References/Specs/Spec_sync_check.md
      - Spec:sync ctrl: docs/7.0 References/Specs/Spec_sync_ctrl.md
  - GridLAB-D Documentation Outline: docs/outline.md
  - reference:
    - ReadMeConfig:
      - authentication: reference/ReadMeConfig/authentication.md
      - getting-started: reference/ReadMeConfig/getting-started.md
      - my-requests: reference/ReadMeConfig/my-requests.md
    - Doxygen: 
        - Groups: gridlabd/group__index.md
        - Structs: gridlabd/structs__index.md
        - Files: gridlabd/files.md
        - Classes: gridlabd/classes.md
        - Hierarchy: gridlabd/hierarchy.md
        - Modules: gridlabd/modules.md
        - Pages: gridlabd/pages.md